sudo: required
language: ruby
services: docker
env:
  global:
  - DOCKER_COMPOSE_VERSION=1.18.0
  - COMMIT=${TRAVIS_COMMIT::8}
  - DUSER=dimmsd
  - REPO="dimmsd/ubuntu-node"
  - NODE_IMAGE="ubuntu-node"
  - MAIN_DOMAIN=example.loc
  - TIMEZONE=Europe/Moscow
  - OWN_USER=dimm
  - OWN_UID=1000
  - OWN_GID=1000
  - NODE_VERSION=node
  - NVM_VERSION=0.34.0
  - NODEIP=172.50.0.100
  - SUBNET=172.50.0.0/24
  - TEST_A=0.1
  - secure: GzBKHSWLIsFH5Be2CuA2QvGk+kf2HNgTCLGZbqKSL9+DyzHzn1i16zv3k+AIg9Ja7sNoGz8nNLoWPj+KBB5GTfNkun0spAme4fA30D9yp3DY8EfkHZVVqDDrFmDPbLwlUslkw5e9p9UlW66y0qxrvfIV0/rzwznUuo+VMB5aE+QJ5HqRq/DkOys7HakZewiO9UU+OCXkNScvFMduK+4eWvwbxpYGISxcxq7ogg8zCSpBf4wqtDqYp3jBISF8g70WxKnkQL+rTwLm6DSfI7/LyRzPMijz6dq3U20KmHpbFOFsARbHC7aO4WB+KUloFOxLxPXZVMWGcGwUOfP//2N7Ok3yw3pX5lM3da2QHFbvvs44jucdRNRDYVIXCWRCRLyvWiexxKGsWI7tVBePQ+Agn6ILTjkTFd2j42M+tBuNJy1UlJGgU3F0gkE5S1h2Haq1B8SEsuNGVbBlE/e+Ps5cYynoOi7ggayJeWPGydAQnUqpylNWm/qMvJVIN6Tiv7GTuRL9nqER+jDb8RnUGQ9njec0PyJG1ZvccoR15UzAArz3sBHpPcUkrRfBorCXPW22fZuvCdVlT+88wTBDI4KNrz7sDATzitli89A6L+Ku3ucEON2xMouSD/qkJmCnmpphQmsLVz8AG9xdO/Pm0Bp4lkFHO/wQ3aYZmzpWLbGAPO0=
  - secure: jGULFPHLRlkvwTdtMSxnCH3kUR6Yb8U8TTONmp4N8udc+ON2Me9VrOgPgisHpiU2zXzxVtizlqwqv8SrMb9BsH5iuSw+mPG88BWCLaXeY8qHUO3VPvJK6e/OgnfWz1cbD4YPmrDBgSDSOwzwjvDUSLYg+qltYXzRVuplwCFIOEGj+yWkGg0qDxW9kaOa6HvsjRpZhe/ZmlvQb4BONgkLh+SlI088OKnu4xbfH1UESq9B5WqrLJ3SD/YBQrPKUhgz4kSwr62AbGv1rMFCdUcVeq0ChEs5bCxUFasJ6H31UkCExPrfhhvb6OeYceJU6SUiUt3D27TeVr20ruwL6c7kWov1sOrTIGNL/YiWDX3e35BWDrhM4dAH/WV4gyp03NDo5aeCJ/3cDaGn08d5PmWtKOj7nb58dOd5hORYqLYQ5cLyow+IBNMBLCM4nIZ+5LRbzYR+8G5iS1Bne79ZIpuIFATGjojJ97CEhZnoj2MZaMC4olQbDdPyyy0yF15oZ9YzDclPrUIRewS4u7NXmZvhcGwvT10aZ0Q5DfnSfYlwRrQBqBHOuPmP1dFyFBT1nzPQzO2I0klmVv4lkdjMnjViq2FqpdzxYK2sEQZjiIzhXBDbu8B9g/M4zRl2alJpGDsMj56/NdUoxzMzthoYTdH/DEgXuZF7P+PGS05C6Od5dv0=
  - secure: jWknkuOtAjHrSXFHN/UcSUgh11twEKDGFa0J/M7fI5ZMWK8gSlVyZ/LH4fqVe8ydzi4ridWi+qWqiNm1krI2sDNPWdHliAYKkWydfOY8JdhSPrT5JJSfh0lMQAu2X02ixnPfAdW+jIwN1hA1Kqbh7dcnZNMHKoD85ptcVk8VxpUYvQC41ZNfvtIsGA0GHpf6s7Ao7YDXIP3F9jgUUz22Pt+IYe8P9EQEDXrzH6bOw8BXpFzr3T/Jo1NAsD5Ei7Jij0Xa9P9mi04wC6hXDwJmxrUmNiDl6yusLmzO7M3OHlrFizM2O57gprcNx+yH+NbG2MbDZCHKRSqA2J8EqZbF9u/HSA9mx43IBf9cAlwr3JPaPEVQc8nqhQvoX9Q1BGbQIXR97eowGR3OgzDZWz8X9Fs7tC21Qfkf8UIED0yyvuOXh3CNEly8j7tpO5uB6Hwd3kFw0A10dXJvPJPCsiNeSQZFOw/2YfwhiXmxrlnTtXVutVAw3gpW7j+QmUlctU1YnYEnyfqkCYaYItgd8ayRncPp4wT72IXGtXxEyGbKSYkEyUT4U9NhlG42xv06J/cBn+zl6zxr5wVC8wJlXDmHPFKHo4JGVtVNIERc63uQI24WkfeN44OyJxUD+DPnnkKDwG4APPW5cTDtDW0P+cXpGzr/BNmtLhatzuRxxQ+BnbA=
  matrix:
  - UBUNTU_VERSION=16.04
  - UBUNTU_VERSION=18.04
  - UBUNTU_VERSION=20.04
before_install:
- sudo apt update -y
- sudo apt install --only-upgrade docker-ce -y
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- env > .env
- chmod 777 -R ./node-user
- chmod 777 -R ./www
install:
- make build
- make install-node
- make install-demo
- make up
script:
- docker images | grep -q $NODE_IMAGE
- docker ps | grep -q node-$MAIN_DOMAIN
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=$UBUNTU_VERSION
- docker tag $NODE_IMAGE:$TAG $REPO:$TAG
- docker push $REPO:$TAG
